docs: add webhook code sample
googleapis/nodejs-dialogflow-cx pull request #177
Opened 2021-09-15 15:59 UTC by galz10

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-dialogflow-cx/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2021-10-06 15:45 UTC, JustinBeckwith requested changes

2021-10-06 15:45 UTC, JustinBeckwith commented on samples/webhooks.js
> +  console.log(request);
Guessing we don't want the console.logs in the sample code

2021-10-06 15:45 UTC, JustinBeckwith commented on samples/webhooks.js
> +  if (tag === 'Default Welcome Intent') {
Feels like we could do a simple string assignment based on the tag, and then create the `jsonResponse` object once using that text?

2021-10-14 18:02 UTC, galz10 commented on samples/webhooks.js
> +exports.handleWebhook = (request, response) => {
This code is going to be in google.docs so there will be information of what you need to do to run this. Also to run this you'd just copy past into cloud function.

2021-10-25 18:38 UTC, JustinBeckwith approved these changes

2021-10-25 19:00 UTC, merged